export const EXECUTIVES = [
  {
    id: "E1",
    first: "Kian",
    last: "Kazranian",
    major: "Mathematics Economics",
    grad: "2026",
    role: "Co-President",
    slug: "Kian_Kazranian",
    linkedIn: "https://www.linkedin.com/in/kiankazranian",
    email: null,
  },
  {
    id: "E2",
    first: "Ammar",
    last: "Wahab",
    major: "Business Economics",
    grad: "2026",
    role: "Co-President",
    slug: "Ammar_Wahab",
    linkedIn: "https://www.linkedin.com/in/ammarwahab",
    email: null,
  },
  {
    id: "E3",
    first: "Rianne",
    last: "Ke",
    major: "Environmental Science",
    grad: "2028",
    role: "VP of External Relations",
    slug: "Rianne_Ke",
    linkedIn: "https://www.linkedin.com/in/rianne-ke-3b89192a5",
    email: null,
  },
  {
    id: "E4",
    first: "Carlie",
    last: "Harwood",
    major: "Business Economics",
    grad: "2028",
    role: "VP of Internal Relations",
    slug: "Carlie_Harwood",
    linkedIn: "https://www.linkedin.com/in/carlie-harwood",
    email: null,
  },
  {
    id: "E5",
    first: "Kit",
    last: "He",
    major: "Film & Television",
    grad: "2027",
    role: "VP of Internal Relations",
    slug: "Kit_He",
    linkedIn: "https://www.linkedin.com/in/kit-jiaying-he-542260298/",
    email: null,
  },
  {
    id: "E6",
    first: "Ryan",
    last: "Kobayashi",
    major: "Economics & Communications",
    grad: "2028",
    role: "Director of Membership",
    slug: "Ryan_Kobayashi",
    linkedIn: "https://www.linkedin.com/in/ryan-kobayashi-ucla",
    email: null,
  },
  {
    id: "E7",
    first: "Liam",
    last: "Holmes",
    major: "Mathematics Economics",
    grad: "2028",
    role: "Director of Consulting",
    slug: "Liam_Holmes",
    linkedIn: "https://www.linkedin.com/in/liam-holmes-baa378251",
    email: null,
  },
  {
    id: "E8",
    first: "Jai",
    last: "Raman",
    major: "Music Industry & Economics",
    grad: "2028",
    role: "Director of Finance",
    slug: "Jai_Raman",
    linkedIn: "https://www.linkedin.com/in/jairaman06",
    email: null,
  },
  {
    id: "E9",
    first: "Sebastine",
    last: "Chun",
    major: "Political Science",
    grad: "2028",
    role: "Director of Marketing",
    slug: "Sebastine_Chun",
    linkedIn: "https://www.linkedin.com/in/sebastinechun",
    email: null,
  },
  {
    id: "E10",
    first: "Connor",
    last: "Chung",
    major: "Computer Science + Linguistics",
    grad: "2028",
    role: "Director of Tech",
    slug: "Connor_Chung",
    linkedIn: "https://www.linkedin.com/in/connorjchung",
    email: null,
  },
];

export const ADVISORYBOARD = [
  {
    id: "1",
    first: "Adrienne",
    last: "Lee",
    major: "Public Affairs & Statistics and Data Science",
    grad: "2027",
    role: "Former President",
    slug: "Adrienne_Lee",
    linkedIn: "https://www.linkedin.com/in/adrienne-lee-11457026b/",
    email: "adrienneleehs@gmail.com",
  },
  {
    id: "2",
    first: "Giselle",
    last: "Carlos",
    major: "Political Science & Minor in Film and TV",
    grad: "2027",
    role: "Former Vice President of Internal",
    slug: "Giselle_Carlos",
    linkedIn: "https://www.linkedin.com/in/giselle-carlos-03449b298/",
    email: "gisellecarlos@ucla.edu",
  },
  {
    id: "3",
    first: "Caleb",
    last: "Chor",
    major: "Cognitive Science & Philosophy",
    grad: "2027",
    role: "Former Vice President of Membership",
    slug: "Caleb_Chor",
    linkedIn: "https://www.linkedin.com/in/caleb-chor/",
    email: "calebchor27@ucla.edu",
  },
  {
    id: "4",
    first: "Bek",
    last: "Tan",
    major: "Cognitive Science",
    grad: "2027",
    role: "Former Vice President of Projects",
    slug: "Bek_Tan",
    linkedIn: "https://www.linkedin.com/in/bektan/",
    email: "bekytan13@ucla.edu",
  },
  {
    id: "5",
    first: "Kimberly",
    last: "Cui",
    major: "Statistics and Data Science & Economics",
    grad: "2027",
    role: "Former Vice President of Finance",
    slug: "Kimberly_Cui",
    linkedIn: "https://www.linkedin.com/in/kimberlycui/",
    email: "kcui@ucla.edu",
  },
  {
    id: "6",
    first: "Ethan",
    last: "Huang",
    major: "Computer Science",
    grad: "2027",
    role: "Former Vice President of Technology",
    slug: "Ethan_Huang",
    linkedIn: "https://www.linkedin.com/in/ethanwhuang/",
    email: "ewchuang@ucla.edu",
  },
  {
    id: "7",
    first: "Allison",
    last: "McCabe",
    major: "Cognitive Science",
    grad: "2027",
    role: "Former Vice President of Marketing",
    slug: "Alli_Mccabe",
    linkedIn: "https://www.linkedin.com/in/allison-mccabe-2b1aa420b/",
    email: "alliymcc@ucla.edu",
  },
  {
    id: "8",
    first: "Dlency",
    last: "Zheng",
    major: "Economics & Music Industry",
    grad: "2027",
    role: "Former Vice President of External Affairs",
    slug: "Dlency_Zheng",
    linkedIn: "https://www.linkedin.com/in/dlencyzheng/",
    email: "dlencyz@gmail.com",
  },
];

export const PRODUCT_MANAGERS = [];

export const CONSULTANTS = [
  {
    id: "204",
    first: "Riya",
    last: "Patel",
    major: "Business Economics & Digital Humanities",
    grad: "2027",
    role: "Consultant",
    slug: "Riya_Patel",
    linkedIn: "https://www.linkedin.com/in/riya-patel-555977281",
  },
  {
    id: "205",
    first: "Heidi",
    last: "Yu",
    major: "Statistics & Data Science",
    grad: "2026",
    role: "Consultant",
    slug: "Heidi_Yu",
    linkedIn: "https://www.linkedin.com/in/heidijyyu",
  },
  {
    id: "208",
    first: "Ashlyn",
    last: "Chin",
    major: "Chemical Engineering",
    grad: "2027",
    role: "Consultant",
    slug: "Ashlyn_Chin",
    linkedIn: "https://www.linkedin.com/in/ashlync128",
  },
  {
    id: "209",
    first: "Jesse",
    last: "Acosta-Huerta",
    major: "Business Economics",
    grad: "2026",
    role: "Consultant",
    slug: "Jesse_Acosta_Huerta",
    linkedIn: "https://www.linkedin.com/in/jesseacosta-huerta",
  },
  {
    id: "210",
    first: "Aidan",
    last: "Singh",
    major: "Economics & Psychology",
    grad: "2026",
    role: "Consultant",
    slug: "Aidan_Singh",
    linkedIn: "https://www.linkedin.com/in/aidansingh",
  },
  {
    id: "211",
    first: "Luisa",
    last: "Chen",
    major: "Business Economics & Cognitive Science",
    grad: "2027",
    role: "Consultant",
    slug: "Luisa_Chen",
    linkedIn: "https://www.linkedin.com/in/luisachen05",
  },
  {
    id: "213",
    first: "Tia",
    last: "Breaux",
    major: "Political Science",
    grad: "2027",
    role: "Consultant",
    slug: "Tia_Breaux",
    linkedIn: "https://www.linkedin.com/in/tia-breaux",
  },
  {
    id: "214",
    first: "Jack",
    last: "Booher",
    major: "Business Economics",
    grad: "2028",
    role: "Consultant",
    slug: "Jack_Booher",
    linkedIn: "https://www.linkedin.com/in/jack-booher-581aa1258",
  },
  {
    id: "216",
    first: "Anannya",
    last: "Shah",
    major: "Cognitive Science",
    grad: "2028",
    role: "Consultant",
    slug: "Anannya_Shah",
    linkedIn: "https://www.linkedin.com/in/anannya-shah",
  },
  {
    id: "218",
    first: "Vivaan",
    last: "Turakhia",
    major: "Economics & Psychology",
    grad: "2027",
    role: "Consultant",
    slug: "Vivaan_Turakhia",
    linkedIn: "https://www.linkedin.com/in/vivaanturakhia",
  },
  {
    id: "219",
    first: "Matthew",
    last: "Ybarra",
    major: "Economics",
    grad: "2028",
    role: "Consultant",
    slug: "Matthew_Ybarra",
    linkedIn: "https://www.linkedin.com/in/matthew-a-ybarra",
  },
  {
    id: "220",
    first: "Gina",
    last: "Decas",
    major: "Business Economics",
    grad: "2027",
    role: "Consultant",
    slug: "Gina_Decas",
    linkedIn: "https://www.linkedin.com/in/gina-decas-0428a8338",
  },
  {
    id: "230",
    first: "Khushi",
    last: "Tekriwal",
    major: "Statistics and Data Science & Mathematics",
    grad: "2027",
    role: "Consultant",
    slug: "Khushi_Tekriwal",
    linkedIn: "https://www.linkedin.com/in/khushi-tekriwal/details/education/",
  },
  {
    id: "223",
    first: "Piper",
    last: "Tenney",
    major: "Business Economics",
    grad: "2028",
    role: "Consultant",
    slug: "Piper_Tenney",
    linkedIn: "https://www.linkedin.com/in/piper-tenney-b735b0276/",
  },
  {
    id: "224",
    first: "Kalani",
    last: "Caetano",
    major: "Statistics and Data Science & Economics",
    grad: "2027",
    role: "Consultant",
    slug: "Kalani_Caetano",
    linkedIn: "https://www.linkedin.com/in/kalanicaetano/",
  },
  {
    id: "225",
    first: "Kayla",
    last: "Kinsey",
    major: "Cognitive Science & Minor in Film/Digital Media",
    grad: "2028",
    role: "Consultant",
    slug: "Kayla_Kinsey",
    linkedIn: "https://www.linkedin.com/in/kayla-kinsey-015343331/",
  },
  {
    id: "228",
    first: "Priyal",
    last: "Sharma",
    major: "Statistics and Data Science",
    grad: "2027",
    role: "Consultant",
    slug: "Placeholder",
    linkedIn: "https://www.linkedin.com/in/priyalsh/",
  },
  {
    id: "222",
    first: "Danny",
    last: "Guo",
    major: "Statistics and Data Science & Economics",
    grad: "2028",
    role: "Consultant",
    slug: "Placeholder",
    linkedIn: "https://www.linkedin.com/in/bohan-guo-9078a8326/",
  },
  {
    id: "229",
    first: "Irvin",
    last: "Qi",
    major: "Computer Science",
    grad: "2027",
    role: "Consultant",
    slug: "Irvin_Qi",
    linkedIn: "https://www.linkedin.com/in/irvin-qi",
  },
];
